server {
    listen 8080;
    root /usr/share/nginx/html;

    gzip on;
    gzip_types text/html application/javascript text/css audio/ogg;

    location ~* \.(js|png|mp3|ogg|txt)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
